[master] added Lesson 16
panser81/java pull request #16
Opened 2023-01-10 14:23 UTC by spanteleyko

2023-01-13 07:42 UTC, aperavoznikau-idt requested changes

2023-01-13 07:42 UTC, aperavoznikau-idt commented on Lesson16/src/com/gmail/panser81/lesson16/helpers/Helper.java
> +    private static Random RAND = new Random();
please use final modificator

2023-01-13 07:42 UTC, aperavoznikau-idt commented on Lesson16/src/com/gmail/panser81/lesson16/services/Info.java
> +        String currentDateTimeString = dateTimeFormatter.format(now);
Better to create method for this in helper class

2023-01-13 07:42 UTC, aperavoznikau-idt commented on Lesson16/src/com/gmail/panser81/lesson16/services/Info.java
> +            e.printStackTrace();
general approach - print message + print stacktrace

2023-01-13 07:42 UTC, aperavoznikau-idt commented on Lesson16/src/com/gmail/panser81/lesson16/services/impl/ArrayLessonThreadImpl.java
> +    private static final int MAX_VALUE = 100;
Better to use separate class for constants if we have a lot of objects which we create from this class

2023-01-13 07:42 UTC, aperavoznikau-idt commented on Lesson16/src/com/gmail/panser81/lesson16/services/impl/CreateFileLessonServiceImpl.java
> +        Thread[] threads = new Thread[THREADS_COUNT];
For Java, we prefer to use collection, not array for each case

2023-01-13 07:42 UTC, aperavoznikau-idt commented on Lesson16/src/com/gmail/panser81/lesson16/services/impl/ArrayLessonThreadImpl.java
> +public class ArrayLessonThreadImpl extends Thread {
Thread is not a Service class. Naming should be appropriate - ArrayLessonThread is enough

2023-01-13 09:16 UTC, spanteleyko commented on Lesson16/src/com/gmail/panser81/lesson16/helpers/Helper.java
> +    private static Random RAND = new Random();
added

2023-01-13 09:17 UTC, spanteleyko commented on Lesson16/src/com/gmail/panser81/lesson16/services/Info.java
> +        String currentDateTimeString = dateTimeFormatter.format(now);
created helper method

2023-01-13 09:17 UTC, spanteleyko commented on Lesson16/src/com/gmail/panser81/lesson16/services/Info.java
> +            e.printStackTrace();
fixed

2023-01-13 09:17 UTC, spanteleyko commented on Lesson16/src/com/gmail/panser81/lesson16/services/impl/ArrayLessonThreadImpl.java
> +    private static final int MAX_VALUE = 100;
created a static class

2023-01-13 09:17 UTC, spanteleyko commented on Lesson16/src/com/gmail/panser81/lesson16/services/impl/CreateFileLessonServiceImpl.java
> +        Thread[] threads = new Thread[THREADS_COUNT];
used a List

2023-01-13 09:17 UTC, spanteleyko commented on Lesson16/src/com/gmail/panser81/lesson16/services/impl/ArrayLessonThreadImpl.java
> +public class ArrayLessonThreadImpl extends Thread {
renamed

2023-01-16 08:43 UTC, aperavoznikau-idt approved these changes

2023-01-16 08:45 UTC, merged