[master] added Lesson07
panser81/java pull request #7
Opened 2022-12-14 13:27 UTC by panser81

2022-12-15 04:27 UTC, aperavoznikau-idt requested changes

2022-12-15 04:27 UTC, aperavoznikau-idt commented on Lesson07/src/com/gmail/panser81/lesson07/part1/Circle.java
> +    private static final double PI = 3.1415;
Better to use Math.PI

2022-12-15 04:27 UTC, aperavoznikau-idt commented on Lesson07/src/com/gmail/panser81/lesson07/part1/Figure.java
> +    }
Better to use abstract method

2022-12-15 04:27 UTC, aperavoznikau-idt commented on Lesson07/src/com/gmail/panser81/lesson07/part1/Figure.java
> +    private double perimeter;
These are calculated parameters. Better don't use as a fields

2022-12-15 09:36 UTC, panser81 commented on Lesson07/src/com/gmail/panser81/lesson07/part1/Circle.java
> +    private static final double PI = 3.1415;
fixed

2022-12-15 09:36 UTC, panser81 commented on Lesson07/src/com/gmail/panser81/lesson07/part1/Figure.java
> +    private double perimeter;
updated

2022-12-22 10:16 UTC, aperavoznikau-idt approved these changes

2022-12-22 10:18 UTC, merged